### ISSUE TITLE
Error setting token duration for 1 minute.

### ISSUE THREAD

**Issue by alexcar** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#5] opened 2017-12-09 22:07 UTC
After following all the steps in "Testing it up" on page 435, changes made to the quiz are not applied.

**Comment by Darkseal** [comment] 2017-12-16 14:31
Hello there and thank you for purchasing the book.

Did you manage to reproduce the error using the GitHub code for chapter 09?

**Comment by Darkseal** [comment] 2018-01-05 23:32
Hello there, I'm closing this issue since there have been no feedbacks in a while. I just tested the whole Chapter 09 GitHub code and it seems to be working properly, feel free to re-open the issue if you can give additional info regarding your problem.

**Closed by Darkseal** 2018-01-05 23:32 UTC
